### ISSUE TITLE
Error: Invalid Podimo credentials or Podimo is unreachable

### ISSUE THREAD

**Issue by pven** [ThijsRay/podimo#23] opened 2023-10-04 12:48 UTC
After restarting the docker container I get this error. Since I have no idea how to check if podimo is online or what credentials are wrong, I wanted to log an issue for this. As far as I am aware my credentials are valid, otherwise I would get the popup.

```
[2023-10-04 12:41:12 +0000] [1] [INFO] Running on http://0.0.0.0:12104 (CTRL + C to quit)
AuthorizationPreregisterUser
An error occurred: Invalid Podimo credentials or Podimo is unreachable
Traceback (most recent call last):
  File "/src/main.py", line 97, in check_auth
    await client.podimoLogin(scraper)
  File "/src/podimo/client.py", line 106, in podimoLogin
    await self.getPreregisterToken(scraper)
  File "/src/podimo/client.py", line 83, in getPreregisterToken
    result = await self.post(headers, query, variables, scraper)
  File "/src/podimo/client.py", line 58, in post
    raise ValueError("Invalid Podimo credentials or Podimo is unreachable")
ValueError: Invalid Podimo credentials or Podimo is unreachable
```

**Comment by pven** [comment] 2023-10-04 20:14
Forgot to mention: I receive new episodes, so it looks like it is working.

**Comment by pven** [comment] 2023-10-05 05:18
Looks like it is broken:

```
ChannelEpisodesQuery
Error while fetching podcasts: Invalid Podimo credentials or Podimo is unreachable
```

In the Podimo-app it works.

**Comment by ThijsRay** [comment] 2023-10-05 09:18
Unfortunately, I cannot reproduce your issue reliably. I have pushed some changes to main, that enable more explicit logging in case when something goes wrong. Some endpoints seem somewhat flaky, which might cause the errors to appear.

**Comment by pven** [comment] 2023-10-05 13:14
I think Podimo did something to the podcast id. When I want to look it up, it is not in the URL anymore. Now the showname is in there. 

(I get back to this later on.)

**Comment by pven** [comment] 2023-10-05 19:15
I updated to the latest version.

This is the error:
```
RuntimeError: Podimo returned an error code. Response code was: 403 for query "query AuthorizationPreregister..."
AuthorizationPreregisterUser
An error occurred: Podimo returned an error code. Response code was: 403 for query "query AuthorizationPreregister..."
Traceback (most recent call last):
  File "/src/main.py", line 97, in check_auth
    await client.podimoLogin(scraper)
  File "/src/podimo/client.py", line 115, in podimoLogin
    await self.getPreregisterToken(scraper)
  File "/src/podimo/client.py", line 87, in getPreregisterToken
    result = await self.post(headers, query, variables, scraper)
  File "/src/podimo/client.py", line 60, in post
    raise RuntimeError(f"Podimo returned an error code. Response code was: {response.status_code} for query \"{query.strip()[:30]}...\"")
RuntimeError: Podimo returned an error code. Response code was: 403 for query "query AuthorizationPreregister..."
```

I am sure the credentials are ok since it worked earlier.

**Comment by tobiasdosdal** [comment] 2023-10-06 15:36
Podimo is watching this repo i think :D

**Comment by pven** [comment] 2023-10-09 07:02
Am I currently the only one with issues?

**Comment by tobiasdosdal** [comment] 2023-10-09 09:28
no also me

**Comment by pven** [comment] 2023-10-10 20:19
Some episodes come thru, but most of them don't.

**Comment by ThijsRay** [comment] 2023-10-11 09:05
It looks like a rather strict rate limiting scheme has been put in place, which might explain why some episodes come through, but others don't

**Comment by veelineen** [comment] 2023-10-12 20:48
> I think Podimo did something to the podcast id. When I want to look it up, it is not in the URL anymore. Now the showname is in there.
> 
> (I get back to this later on.)

It's still there but you need to open the webplayer at open.podimo.com

**Comment by pven** [comment] 2023-10-17 17:39
Since all the issues, I am affraid this alternative for the rss-feed is over?

**Comment by pven** [comment] 2023-10-22 17:18
Since a week or so, there are no episodes coming thru anymore (as in: none).

**Comment by ThijsRay** [comment] 2023-10-23 14:22
I am aware of that. [I began working on a completely different approach](https://github.com/ThijsRay/podimo/tree/using_puppeteer). This will likely keep working for a very long time, but progress has been slow because of there is a major difference between how the web player and how the app works.

**Comment by pven** [comment] 2023-11-02 07:42
If you need testers: let me know. Until then I am suffering with the Podimo-app. ;-)

**Comment by ArjanM83** [comment] 2023-11-10 16:16
I can confirm the authorization is no longer functioning. Even tried creating a new account with 3-month subscription.

**Comment by Walter-o** [comment] 2024-01-27 00:01
Guys

Podimo just made some minor changes to their API.

I'll look if i can fix it in this repo soon.

For this podcast downloader repo i already fixed it and can download in bulk from Podimo: https://github.com/jo1gi/audiobook-dl/pull/86

**Comment by thebang2** [comment] 2024-03-10 19:44
Any progress so far?

**Comment by ThijsRay** [comment] 2024-03-12 14:21
I'm closing this issue for now. The original issue can be solved by either [running behind a proxy](https://github.com/ThijsRay/podimo?tab=readme-ov-file#bot-detection) or from an network with a very good reputation at Cloudflare. Unfortunately, the other approach using Puppeteer I mentioned earlier doesn't work. Those changes would force you to send up to 100s of additional requests to Podimo's servers to retrieve a podcast feed, while the current approach can achieve the same with just a handful of requests.

If the issue pops up again, don't hesitate to open a new issue!

**Closed as completed by ThijsRay** 2024-03-12 14:21 UTC
