### ISSUE TITLE
Feed asks for username and password

### ISSUE THREAD

**Issue by joeyboon** [ThijsRay/podimo#17] opened 2023-08-10 17:34 UTC
Hi,

I've been using your server to load a podcast in AntennaPod on Android, but since a couple of weeks the feed won't load but instead asks for authentication (username and password). Any idea why the previous working feed suddenly would stop working? I checked and my subscription is still valid and used your tool to create the feed once again, I'm experiencing the same issue.

**Comment by ThijsRay** [comment] 2023-08-11 08:49
This is a known issue. Cloudflare seems to be blocking the IP ranges from the provider where I'm hosting the tool. Hosting it yourself does seem to work, see https://github.com/ThijsRay/podimo/issues/13
I will fix this in the future but it will take some time.

**Comment by joeyboon** [comment] 2023-08-11 08:52
Sorry I read the ticket, but did not realize the expected behavior would be for my app to ask for credentials. I'll look into selfhosting :) Thanks!

**Comment by ThijsRay** [comment] 2023-08-11 09:07
I agree that the behavior is a bit strange, and it could definitely be improved. It currently tries to login with the given credentials, and notices that it fails (because the server is not allowed to access Podimo, it gets a forbidden error). This is interpreted as "Credentials are invalid, please enter correct credentials". There is probably a better way to handle this case from a UX perspective.
I'll reopen the issue until this has been changed.

**Comment by alego500** [comment] 2023-08-24 11:15
I reproduced the same issues in Pocket Casts. Even with a fresh subscription.
 It no longer loads anything.

If I go to the xml directly though a browser I also get the login prompt. After entering username and password i'm just prompted for the username and password again.

<img width="1461" alt="Podimo" src="https://github.com/ThijsRay/podimo/assets/7690425/e44c1dec-1e48-4952-b6f2-1deac81b328c">

**Comment by pven** [comment] 2023-09-11 18:05
> I reproduced the same issues in Pocket Casts. Even with a fresh subscription. It no longer loads anything.
> 
> If I go to the xml directly though a browser I also get the login prompt. After entering username and password i'm just prompted for the username and password again.
> 
> <img alt="Podimo" width="1461" src="https://user-images.githubusercontent.com/7690425/262955639-e44c1dec-1e48-4952-b6f2-1deac81b328c.png">

I have exactly the same issue on my local installation (in Docker). Is there a solution for this? Right now I am convicted to the Podimo-app, that sucks ... ;-)

**Comment by ThijsRay** [comment] 2023-09-18 12:25
The [latest release](https://github.com/ThijsRay/podimo/releases/tag/v0.2.2) fixes the issue, at least for the time being. I'll close this issue for now.

**Closed as completed by ThijsRay** 2023-09-18 12:25 UTC

**Comment by pven** [comment] 2023-09-25 12:33
I am using the latest version locally, but it still asks for a user and password (same as before).

**Comment by pven** [comment] 2023-09-26 18:32
Sorry to kick this issue again, but I am quite sure I am entering the proper credentials but the popup is back. Is it me?

**Comment by ThijsRay** [comment] 2023-09-27 14:32
The tool has yet again been blocked by Podimo/Cloudflare, that is why you see the popup again. If anybody has suggestions for a workaround, please don't hesitate to open an issue or a pull request.

**Comment by pven** [comment] 2023-10-01 16:03
With the fix of @GlJS it works again. 👍
